import React from 'react';
import type { ViewStyle, TextStyle } from 'react-native';
export type CollapseVariant = 'default' | 'bordered' | 'elevated' | 'flat';
export type CollapseSize = 'small' | 'medium' | 'large' | undefined;
export type CollapseIconPosition = 'left' | 'right';
interface CollapseProps {
    title?: string;
    children?: React.ReactNode;
    defaultExpanded?: boolean;
    disabled?: boolean;
    variant?: CollapseVariant;
    size?: CollapseSize;
    backgroundColor?: string;
    titleColor?: string;
    borderColor?: string;
    borderRadius?: number;
    disabledBackgroundColor?: string;
    disabledTitleColor?: string;
    disabledBorderColor?: string;
    fullWidth?: boolean;
    alignSelf?: 'auto' | 'flex-start' | 'flex-end' | 'center' | 'stretch';
    style?: ViewStyle;
    titleStyle?: TextStyle;
    contentStyle?: ViewStyle;
    containerStyle?: ViewStyle;
    onToggle?: (expanded: boolean) => void;
    animated?: boolean;
    animationDuration?: number;
    leftIcon?: React.ReactNode;
    rightIcon?: React.ReactNode;
    customExpandIcon?: React.ReactNode;
    customCollapseIcon?: React.ReactNode;
    iconPosition?: CollapseIconPosition;
    iconSpacing?: number;
    customHeader?: React.ReactNode;
    accessibilityLabel?: string;
    accessibilityHint?: string;
    accessibilityRole?: 'button' | 'none';
    shadow?: boolean;
    shadowColor?: string;
    shadowOffset?: {
        width: number;
        height: number;
    };
    shadowOpacity?: number;
    shadowRadius?: number;
    borderWidth?: number;
    borderStyle?: 'solid' | 'dotted' | 'dashed';
    showDivider?: boolean;
    dividerColor?: string;
    dividerWidth?: number;
}
export declare const Collapse: React.FC<CollapseProps>;
export type { CollapseProps };
