import React from 'react';
import type { ViewStyle, TextStyle, GestureResponderEvent } from 'react-native';
import type { TouchableOpacityProps } from 'react-native';
export type CheckBoxVariant = 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'info';
export type CheckBoxSize = 'small' | 'medium' | 'large';
export type CheckBoxShape = 'rounded' | 'square' | 'circle';
interface CheckBoxProps extends TouchableOpacityProps {
    label?: string;
    children?: React.ReactNode;
    checked?: boolean;
    onPress?: (event: GestureResponderEvent) => void;
    onValueChange?: (checked: boolean) => void;
    disabled?: boolean;
    disableColorChange?: boolean;
    variant?: CheckBoxVariant;
    size?: CheckBoxSize;
    shape?: CheckBoxShape;
    backgroundColor?: string;
    checkedBackgroundColor?: string;
    textColor?: string;
    borderColor?: string;
    checkedBorderColor?: string;
    borderRadius?: number;
    width?: number;
    height?: number;
    disabledBackgroundColor?: string;
    disabledTextColor?: string;
    disabledBorderColor?: string;
    disabledCheckedBackgroundColor?: string;
    disabledCheckedBorderColor?: string;
    activeTextStyle?: TextStyle;
    activeContainerStyle?: ViewStyle;
    activeCheckboxStyle?: ViewStyle;
    activeBackgroundColor?: string;
    activeTextColor?: string;
    activeBorderColor?: string;
    activeBorderRadius?: number;
    activeBorderWidth?: number;
    activeShadow?: boolean;
    activeShadowColor?: string;
    activeShadowOffset?: {
        width: number;
        height: number;
    };
    activeShadowOpacity?: number;
    activeShadowRadius?: number;
    fullWidth?: boolean;
    alignSelf?: 'auto' | 'flex-start' | 'flex-end' | 'center' | 'stretch';
    labelPosition?: 'left' | 'right';
    textStyle?: TextStyle;
    containerStyle?: ViewStyle;
    checkboxStyle?: ViewStyle;
    debounceTime?: number;
    activeOpacity?: number;
    customCheckIcon?: React.ReactNode;
    labelSpacing?: number;
    checkIconText?: string;
    checkIconSize?: number;
    checkIconColor?: string;
    checkIconStyle?: TextStyle;
    accessibilityLabel?: string;
    accessibilityHint?: string;
    accessibilityRole?: 'checkbox' | 'button' | 'none';
    pressable?: boolean;
    shadow?: boolean;
    shadowColor?: string;
    shadowOffset?: {
        width: number;
        height: number;
    };
    shadowOpacity?: number;
    shadowRadius?: number;
    borderWidth?: number;
    borderStyle?: 'solid' | 'dotted' | 'dashed';
    indeterminate?: boolean;
    customIndeterminateIcon?: React.ReactNode;
}
declare const CheckBox: React.FC<CheckBoxProps>;
export default CheckBox;
